# Generated by Django 4.2.23 on 2025-09-15 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image_type', models.CharField(choices=[('surveillance', 'Surveillance Image'), ('incident', 'Incident Photo'), ('person', 'Person of Interest'), ('vehicle', 'Vehicle Image'), ('document', 'Document'), ('other', 'Other')], default='other', max_length=20)),
                ('image', models.ImageField(upload_to='uploads/images/%Y/%m/%d/')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('is_public', models.BooleanField(default=False)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uploaded Image',
                'verbose_name_plural': 'Uploaded Images',
                'db_table': 'uploaded_images',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_type', models.CharField(choices=[('login_attempts', 'Login Attempts'), ('active_users', 'Active Users'), ('image_uploads', 'Image Uploads'), ('incident_reports', 'Incident Reports'), ('system_usage', 'System Usage'), ('daily_activity', 'Daily Activity'), ('user_engagement', 'User Engagement')], max_length=50)),
                ('value', models.FloatField()),
                ('metadata', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Analytics Data',
                'verbose_name_plural': 'Analytics Data',
                'db_table': 'analytics_data',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['metric_type', 'timestamp'], name='analytics_d_metric__262d3a_idx')],
            },
        ),
    ]
